### ISSUE TITLE
I getting error with POST and PUT request. 

### ISSUE THREAD

**Issue by jhakamlesh** [kevinem/places-scout-php#1]
While a POST and PUT request to the API am getting this error : 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://apihost1.placesscout.com/clients` resulted in a `400 NotEmpty` response: {"responseStatus":{"errorCode":"NotEmpty","message":"Name is required.","errors":[{"errorCode":"NotEmpty","fieldName":"N (truncated...) ' in C:\xampp\htdocs\FCS\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:111 Stack trace: #0 C:\xampp\htdocs\FCS\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\FCS\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\FCS\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\xampp\htdocs\FCS\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{c in C:\xampp\htdocs\FCS\PlacesScout.php on line 84

My Code is : 

 `
<?php
    $clients = $placesScout->get('/clients');

    $client = $placesScout->post('/clients', [
        //Some data
//        "url" => $_POST['url'],
//        "Url" => 'https://iaptris.com/fcs/',
//        "Session_id" => $_POST['session_id'],
//        "Name" => $_POST['name'],
//        "Phone" => $_POST['phone'],
//        "Email" => $_POST['email']
            'body' => array(
                "Url" => 'https://iaptris.com/fcs/',
                "Session_id" => $_POST['session_id'],
                "name" => $_POST['name'],
                "phone" => $_POST['phone'],
                "email" => $_POST['email']
            )
    ]);
    $rankingReport = $placesScout->put("/rankingreports/1", [
       //Some data
        json_encode($client)
    ]);
//Or use helper classes to build request
    $clients = new PlacesScoutClients($placesScout);
    echo 'dumping responce';
    $response = $clients->lists();
    echo '<pre>';
    print_r($response);
    echo '<pre><br><br><br>';
    $rankingReport = new PlacesScoutRankingReports($placesScout);
    echo 'dumping ranking report';
    $rankingReport->update('1', [
            //Some data
    ]);
    echo '<pre>';
    print_r($rankingReport);
    echo '<pre>';
}
?>`

My be i am not passing the data in right way, please help

**Comment by kevinem** [comment]
From the error message, it seems the data being sent isn't valid. The error says "message":"Name is required.". Check to see if the fields that are required are not null.
